# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\albru\Documents\navantazhennya_2.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(990, 861)
        MainWindow.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(800, 80, 121, 31))
        self.pushButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton.setObjectName("pushButton")
        self.comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox.setGeometry(QtCore.QRect(140, 80, 171, 31))
        self.comboBox.setObjectName("comboBox")
        self.comboBox_3 = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_3.setGeometry(QtCore.QRect(590, 80, 161, 31))
        self.comboBox_3.setObjectName("comboBox_3")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(350, 170, 121, 31))
        self.pushButton_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_5 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_5.setGeometry(QtCore.QRect(420, 330, 181, 51))
        self.pushButton_5.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_6 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_6.setGeometry(QtCore.QRect(700, 330, 171, 51))
        self.pushButton_6.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_6.setObjectName("pushButton_6")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(180, 20, 141, 31))
        font = QtGui.QFont()
        font.setFamily("Sitka Text")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.comboBox_2 = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_2.setGeometry(QtCore.QRect(140, 130, 171, 31))
        self.comboBox_2.setObjectName("comboBox_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(20, 90, 111, 16))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(20, 140, 111, 16))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(20, 210, 111, 16))
        self.label_5.setObjectName("label_5")
        self.comboBox_4 = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_4.setGeometry(QtCore.QRect(140, 200, 171, 31))
        self.comboBox_4.setObjectName("comboBox_4")
        self.comboBox_5 = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_5.setGeometry(QtCore.QRect(140, 250, 171, 31))
        self.comboBox_5.setObjectName("comboBox_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(20, 260, 111, 16))
        font = QtGui.QFont()
        font.setFamily("Lucida Fax")
        font.setPointSize(8)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.pushButton_7 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_7.setGeometry(QtCore.QRect(140, 330, 171, 51))
        self.pushButton_7.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_7.setObjectName("pushButton_7")
        self.pushButton_8 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_8.setGeometry(QtCore.QRect(700, 160, 171, 51))
        self.pushButton_8.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_8.setObjectName("pushButton_8")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(580, 420, 31, 71))
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setGeometry(QtCore.QRect(500, 10, 21, 291))
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.line_3 = QtWidgets.QFrame(self.centralwidget)
        self.line_3.setGeometry(QtCore.QRect(10, 300, 971, 20))
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(760, 20, 51, 31))
        font = QtGui.QFont()
        font.setFamily("Sitka Text")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.radioButton = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButton.setGeometry(QtCore.QRect(350, 110, 111, 20))
        self.radioButton.setObjectName("radioButton")
        self.radioButton_2 = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButton_2.setGeometry(QtCore.QRect(350, 230, 111, 20))
        self.radioButton_2.setObjectName("radioButton_2")
        self.line_4 = QtWidgets.QFrame(self.centralwidget)
        self.line_4.setGeometry(QtCore.QRect(7, 390, 971, 20))
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.comboBox_Subjects = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_Subjects.setGeometry(QtCore.QRect(140, 430, 171, 31))
        self.comboBox_Subjects.setObjectName("comboBox_Subjects")
        self.pushButton_Calculate_load = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_Calculate_load.setGeometry(QtCore.QRect(710, 640, 171, 51))
        self.pushButton_Calculate_load.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_Calculate_load.setObjectName("pushButton_Calculate_load")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(20, 440, 111, 16))
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        self.label_8.setFont(font)
        self.label_8.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.label_8.setTextFormat(QtCore.Qt.PlainText)
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(390, 430, 111, 16))
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        self.label_9.setFont(font)
        self.label_9.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.label_9.setTextFormat(QtCore.Qt.PlainText)
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(700, 430, 111, 16))
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        self.label_10.setFont(font)
        self.label_10.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.label_10.setTextFormat(QtCore.Qt.PlainText)
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        self.label_11.setGeometry(QtCore.QRect(340, 470, 111, 16))
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        self.label_11.setFont(font)
        self.label_11.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.label_11.setTextFormat(QtCore.Qt.PlainText)
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.centralwidget)
        self.label_12.setGeometry(QtCore.QRect(640, 470, 111, 16))
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        self.label_12.setFont(font)
        self.label_12.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.label_12.setTextFormat(QtCore.Qt.PlainText)
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(self.centralwidget)
        self.label_13.setGeometry(QtCore.QRect(480, 470, 111, 16))
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        self.label_13.setFont(font)
        self.label_13.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.label_13.setTextFormat(QtCore.Qt.PlainText)
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(self.centralwidget)
        self.label_14.setGeometry(QtCore.QRect(800, 470, 111, 16))
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        self.label_14.setFont(font)
        self.label_14.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.label_14.setTextFormat(QtCore.Qt.PlainText)
        self.label_14.setObjectName("label_14")
        self.label_15 = QtWidgets.QLabel(self.centralwidget)
        self.label_15.setGeometry(QtCore.QRect(20, 550, 111, 16))
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        self.label_15.setFont(font)
        self.label_15.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.label_15.setTextFormat(QtCore.Qt.PlainText)
        self.label_15.setObjectName("label_15")
        self.comboBox_Lectors = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_Lectors.setGeometry(QtCore.QRect(140, 540, 171, 31))
        self.comboBox_Lectors.setObjectName("comboBox_Lectors")
        self.pushButton_plus_lector = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_plus_lector.setGeometry(QtCore.QRect(270, 590, 41, 28))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_plus_lector.setFont(font)
        self.pushButton_plus_lector.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_plus_lector.setAutoFillBackground(False)
        self.pushButton_plus_lector.setStyleSheet("color: #42CA3D")
        self.pushButton_plus_lector.setObjectName("pushButton_plus_lector")
        self.comboBox_Assisstents = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_Assisstents.setGeometry(QtCore.QRect(470, 540, 171, 31))
        self.comboBox_Assisstents.setObjectName("comboBox_Assisstents")
        self.label_16 = QtWidgets.QLabel(self.centralwidget)
        self.label_16.setGeometry(QtCore.QRect(350, 550, 111, 16))
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        self.label_16.setFont(font)
        self.label_16.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.label_16.setTextFormat(QtCore.Qt.PlainText)
        self.label_16.setObjectName("label_16")
        self.pushButton_plus_asistent = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_plus_asistent.setGeometry(QtCore.QRect(600, 590, 41, 28))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_plus_asistent.setFont(font)
        self.pushButton_plus_asistent.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_plus_asistent.setStyleSheet("color: #42CA3D")
        self.pushButton_plus_asistent.setObjectName("pushButton_plus_asistent")
        self.listWidget_lectors = QtWidgets.QListWidget(self.centralwidget)
        self.listWidget_lectors.setGeometry(QtCore.QRect(60, 590, 191, 191))
        self.listWidget_lectors.setObjectName("listWidget_lectors")
        self.listWidget_assisstents = QtWidgets.QListWidget(self.centralwidget)
        self.listWidget_assisstents.setGeometry(QtCore.QRect(390, 590, 191, 191))
        self.listWidget_assisstents.setObjectName("listWidget_assisstents")
        self.pushButton_minus_lector = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_minus_lector.setGeometry(QtCore.QRect(270, 630, 41, 28))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_minus_lector.setFont(font)
        self.pushButton_minus_lector.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_minus_lector.setAutoFillBackground(False)
        self.pushButton_minus_lector.setStyleSheet("color: #DE2F23")
        self.pushButton_minus_lector.setObjectName("pushButton_minus_lector")
        self.pushButton_minus_assisstent = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_minus_assisstent.setGeometry(QtCore.QRect(600, 630, 41, 28))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_minus_assisstent.setFont(font)
        self.pushButton_minus_assisstent.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_minus_assisstent.setAutoFillBackground(False)
        self.pushButton_minus_assisstent.setStyleSheet("color: #DE2F23")
        self.pushButton_minus_assisstent.setObjectName("pushButton_minus_assisstent")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 990, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Навантаження кафедри"))
        self.pushButton.setText(_translate("MainWindow", "Відкрити"))
        self.pushButton_2.setText(_translate("MainWindow", "Відкрити"))
        self.pushButton_5.setText(_translate("MainWindow", "Порівняти"))
        self.pushButton_6.setText(_translate("MainWindow", "Створити звіт"))
        self.label_2.setText(_translate("MainWindow", "Файли кафедри"))
        self.label_3.setText(_translate("MainWindow", "Денна 1 семестр "))
        self.label_4.setText(_translate("MainWindow", "Денна 2 семестр"))
        self.label_5.setText(_translate("MainWindow", "Заочна 1 семестр"))
        self.label_6.setText(_translate("MainWindow", "Заочна 2 семестр"))
        self.pushButton_7.setToolTip(
            _translate("MainWindow", "<html><head/><body><p>Конвертувати файли у окремому вікні</p></body></html>"))
        self.pushButton_7.setText(_translate("MainWindow", "Конвертувати"))
        self.pushButton_8.setToolTip(_translate("MainWindow", "<html><head/><body><p>XLS -> XLSX</p></body></html>"))
        self.pushButton_8.setText(_translate("MainWindow", "Конвертувати"))
        self.label_7.setToolTip(
            _translate("MainWindow", "<html><head/><body><p>Робочий навчальний план</p></body></html>"))
        self.label_7.setText(_translate("MainWindow", "РНП"))
        self.radioButton.setText(_translate("MainWindow", "Форма денна"))
        self.radioButton_2.setText(_translate("MainWindow", "Форма заочна"))
        self.pushButton_Calculate_load.setText(_translate("MainWindow", "Розподілити\n"
                                                                        "навантаження"))
        self.label_8.setText(_translate("MainWindow", "           Предмети"))
        self.label_9.setText(_translate("MainWindow", "1 семестр часи:"))
        self.label_10.setText(_translate("MainWindow", "2 семестр часи:"))
        self.label_11.setText(_translate("MainWindow", "Лектора:"))
        self.label_12.setText(_translate("MainWindow", "Лектора:"))
        self.label_13.setText(_translate("MainWindow", "Асистента:"))
        self.label_14.setText(_translate("MainWindow", "Асистента:"))
        self.label_15.setText(_translate("MainWindow", "                Лектор"))
        self.pushButton_plus_lector.setToolTip(_translate("MainWindow",
                                                          "<html><head/><body><p align=\"center\">Додати до списку <span style=\" text-decoration: underline;\">лекторів</span></p></body></html>"))
        self.pushButton_plus_lector.setText(_translate("MainWindow", "+"))
        self.label_16.setText(_translate("MainWindow", "              Асистент"))
        self.pushButton_plus_asistent.setToolTip(_translate("MainWindow",
                                                            "<html><head/><body><p align=\"center\">Додати до списку <span style=\" text-decoration: underline;\">лекторів</span></p></body></html>"))
        self.pushButton_plus_asistent.setText(_translate("MainWindow", "+"))
        self.pushButton_minus_lector.setToolTip(_translate("MainWindow",
                                                           "<html><head/><body><p align=\"center\">Видалити зі списку <span style=\" text-decoration: underline;\">лекторів</span></p></body></html>"))
        self.pushButton_minus_lector.setText(_translate("MainWindow", "x"))
        self.pushButton_minus_assisstent.setToolTip(_translate("MainWindow",
                                                               "<html><head/><body><p align=\"center\">Видалити зі списку <span style=\" text-decoration: underline;\">асистент</span><span style=\" text-decoration: underline;\">ів</span></p></body></html>"))
        self.pushButton_minus_assisstent.setText(_translate("MainWindow", "x"))
