
from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(990, 912)
        MainWindow.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        MainWindow.setStyleSheet("color: #DDE2E6; background-color: #7D8184")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(800, 80, 121, 31))
        self.pushButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton.setStyleSheet("color: #1D0F03")
        self.pushButton.setObjectName("pushButton")
        self.comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox.setGeometry(QtCore.QRect(140, 80, 171, 31))
        self.comboBox.setStyleSheet("background-color: #91939C; color: #173777;")
        self.comboBox.setObjectName("comboBox")
        self.comboBox_3 = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_3.setGeometry(QtCore.QRect(590, 80, 161, 31))
        self.comboBox_3.setStyleSheet("background-color: #91939C; color: #173777")
        self.comboBox_3.setObjectName("comboBox_3")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(350, 170, 121, 31))
        self.pushButton_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_2.setStyleSheet("color: #1D0F03")
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_5 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_5.setGeometry(QtCore.QRect(700, 330, 171, 51))
        self.pushButton_5.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_5.setStyleSheet("color: #1D0F03")
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_6 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_6.setGeometry(QtCore.QRect(140, 330, 171, 51))
        self.pushButton_6.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_6.setStyleSheet("color: #1D0F03")
        self.pushButton_6.setObjectName("pushButton_6")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(180, 20, 141, 31))
        font = QtGui.QFont()
        font.setFamily("Sitka Text")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.comboBox_2 = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_2.setGeometry(QtCore.QRect(140, 130, 171, 31))
        self.comboBox_2.setStyleSheet("background-color: #91939C; color: #173777")
        self.comboBox_2.setObjectName("comboBox_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(20, 90, 111, 16))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(20, 140, 111, 16))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(20, 210, 111, 16))
        self.label_5.setObjectName("label_5")
        self.comboBox_4 = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_4.setGeometry(QtCore.QRect(140, 200, 171, 31))
        self.comboBox_4.setStyleSheet("background-color: #91939C; color: #173777")
        self.comboBox_4.setObjectName("comboBox_4")
        self.comboBox_5 = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_5.setGeometry(QtCore.QRect(140, 250, 171, 31))
        self.comboBox_5.setStyleSheet("background-color: #91939C; color: #173777")
        self.comboBox_5.setObjectName("comboBox_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(20, 260, 111, 16))
        font = QtGui.QFont()
        font.setFamily("Lucida Fax")
        font.setPointSize(8)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.pushButton_8 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_8.setGeometry(QtCore.QRect(700, 160, 171, 51))
        self.pushButton_8.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_8.setStyleSheet("color: #1D0F03")
        self.pushButton_8.setObjectName("pushButton_8")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(590, 420, 31, 71))
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setGeometry(QtCore.QRect(500, 10, 21, 291))
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.line_3 = QtWidgets.QFrame(self.centralwidget)
        self.line_3.setGeometry(QtCore.QRect(10, 300, 971, 20))
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(760, 20, 51, 31))
        font = QtGui.QFont()
        font.setFamily("Sitka Text")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.radioButton = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButton.setGeometry(QtCore.QRect(350, 110, 111, 20))
        self.radioButton.setObjectName("radioButton")
        self.radioButton_2 = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButton_2.setGeometry(QtCore.QRect(350, 230, 111, 20))
        self.radioButton_2.setObjectName("radioButton_2")
        self.line_4 = QtWidgets.QFrame(self.centralwidget)
        self.line_4.setGeometry(QtCore.QRect(7, 390, 971, 20))
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.comboBox_Subjects = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_Subjects.setGeometry(QtCore.QRect(140, 430, 171, 31))
        self.comboBox_Subjects.setStyleSheet("background-color: #91939C; color: #173777")
        self.comboBox_Subjects.setObjectName("comboBox_Subjects")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(20, 440, 111, 16))
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        self.label_8.setFont(font)
        self.label_8.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.label_8.setStyleSheet("")
        self.label_8.setTextFormat(QtCore.Qt.PlainText)
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(390, 430, 111, 16))
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        self.label_9.setFont(font)
        self.label_9.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.label_9.setTextFormat(QtCore.Qt.PlainText)
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(700, 430, 111, 16))
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        self.label_10.setFont(font)
        self.label_10.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.label_10.setTextFormat(QtCore.Qt.PlainText)
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        self.label_11.setGeometry(QtCore.QRect(340, 470, 61, 16))
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        self.label_11.setFont(font)
        self.label_11.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.label_11.setTextFormat(QtCore.Qt.PlainText)
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.centralwidget)
        self.label_12.setGeometry(QtCore.QRect(650, 470, 61, 16))
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        self.label_12.setFont(font)
        self.label_12.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.label_12.setTextFormat(QtCore.Qt.PlainText)
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(self.centralwidget)
        self.label_13.setGeometry(QtCore.QRect(470, 470, 71, 16))
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        self.label_13.setFont(font)
        self.label_13.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.label_13.setTextFormat(QtCore.Qt.PlainText)
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(self.centralwidget)
        self.label_14.setGeometry(QtCore.QRect(780, 470, 71, 16))
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        self.label_14.setFont(font)
        self.label_14.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.label_14.setTextFormat(QtCore.Qt.PlainText)
        self.label_14.setObjectName("label_14")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(50, 500, 881, 361))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.tabWidget.setFont(font)
        self.tabWidget.setStyleSheet("color: #173777")
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.label_15 = QtWidgets.QLabel(self.tab)
        self.label_15.setGeometry(QtCore.QRect(10, 30, 111, 16))
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        self.label_15.setFont(font)
        self.label_15.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.label_15.setStyleSheet("color: #1D0F03")
        self.label_15.setTextFormat(QtCore.Qt.PlainText)
        self.label_15.setObjectName("label_15")
        self.comboBox_Lectors = QtWidgets.QComboBox(self.tab)
        self.comboBox_Lectors.setGeometry(QtCore.QRect(130, 20, 171, 31))
        self.comboBox_Lectors.setStyleSheet("background-color: #91939C;")
        self.comboBox_Lectors.setObjectName("comboBox_Lectors")
        self.listWidget_lectors = QtWidgets.QListWidget(self.tab)
        self.listWidget_lectors.setGeometry(QtCore.QRect(50, 70, 191, 191))
        self.listWidget_lectors.setStyleSheet("background-color: #91939C;")
        self.listWidget_lectors.setObjectName("listWidget_lectors")
        self.label_16 = QtWidgets.QLabel(self.tab)
        self.label_16.setGeometry(QtCore.QRect(340, 30, 111, 16))
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        self.label_16.setFont(font)
        self.label_16.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.label_16.setStyleSheet("color: #1D0F03")
        self.label_16.setTextFormat(QtCore.Qt.PlainText)
        self.label_16.setObjectName("label_16")
        self.listWidget_assisstents = QtWidgets.QListWidget(self.tab)
        self.listWidget_assisstents.setGeometry(QtCore.QRect(380, 70, 191, 191))
        self.listWidget_assisstents.setStyleSheet("background-color: #91939C;")
        self.listWidget_assisstents.setObjectName("listWidget_assisstents")
        self.pushButton_plus_lector = QtWidgets.QPushButton(self.tab)
        self.pushButton_plus_lector.setGeometry(QtCore.QRect(260, 70, 41, 28))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_plus_lector.setFont(font)
        self.pushButton_plus_lector.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_plus_lector.setAutoFillBackground(False)
        self.pushButton_plus_lector.setStyleSheet("color: #42CA3D")
        self.pushButton_plus_lector.setObjectName("pushButton_plus_lector")
        self.pushButton_plus_asistent = QtWidgets.QPushButton(self.tab)
        self.pushButton_plus_asistent.setGeometry(QtCore.QRect(590, 70, 41, 28))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_plus_asistent.setFont(font)
        self.pushButton_plus_asistent.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_plus_asistent.setStyleSheet("color: #42CA3D")
        self.pushButton_plus_asistent.setObjectName("pushButton_plus_asistent")
        self.comboBox_Assisstents = QtWidgets.QComboBox(self.tab)
        self.comboBox_Assisstents.setGeometry(QtCore.QRect(460, 20, 171, 31))
        self.comboBox_Assisstents.setStyleSheet("background-color: #91939C;")
        self.comboBox_Assisstents.setObjectName("comboBox_Assisstents")
        self.pushButton_minus_lector = QtWidgets.QPushButton(self.tab)
        self.pushButton_minus_lector.setGeometry(QtCore.QRect(260, 110, 41, 28))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_minus_lector.setFont(font)
        self.pushButton_minus_lector.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_minus_lector.setAutoFillBackground(False)
        self.pushButton_minus_lector.setStyleSheet("color: #DE2F23")
        self.pushButton_minus_lector.setObjectName("pushButton_minus_lector")
        self.pushButton_minus_assisstent = QtWidgets.QPushButton(self.tab)
        self.pushButton_minus_assisstent.setGeometry(QtCore.QRect(590, 110, 41, 28))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_minus_assisstent.setFont(font)
        self.pushButton_minus_assisstent.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_minus_assisstent.setAutoFillBackground(False)
        self.pushButton_minus_assisstent.setStyleSheet("color: #DE2F23")
        self.pushButton_minus_assisstent.setObjectName("pushButton_minus_assisstent")
        self.pushButton_Calculate_load = QtWidgets.QPushButton(self.tab)
        self.pushButton_Calculate_load.setGeometry(QtCore.QRect(660, 120, 171, 51))
        self.pushButton_Calculate_load.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_Calculate_load.setStyleSheet("color: #1D0F03")
        self.pushButton_Calculate_load.setObjectName("pushButton_Calculate_load")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.listWidget_lectors_db = QtWidgets.QListWidget(self.tab_2)
        self.listWidget_lectors_db.setGeometry(QtCore.QRect(20, 60, 191, 191))
        self.listWidget_lectors_db.setStyleSheet("background-color: #91939C;")
        self.listWidget_lectors_db.setObjectName("listWidget_lectors_db")
        self.listWidget_assisstents_db = QtWidgets.QListWidget(self.tab_2)
        self.listWidget_assisstents_db.setGeometry(QtCore.QRect(310, 60, 191, 191))
        self.listWidget_assisstents_db.setStyleSheet("background-color: #91939C;")
        self.listWidget_assisstents_db.setObjectName("listWidget_assisstents_db")
        self.pushButton_plus_lector_db = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_plus_lector_db.setGeometry(QtCore.QRect(230, 60, 41, 28))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_plus_lector_db.setFont(font)
        self.pushButton_plus_lector_db.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_plus_lector_db.setAutoFillBackground(False)
        self.pushButton_plus_lector_db.setStyleSheet("color: #42CA3D")
        self.pushButton_plus_lector_db.setObjectName("pushButton_plus_lector_db")
        self.pushButton_Save_db = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_Save_db.setGeometry(QtCore.QRect(400, 270, 141, 41))
        self.pushButton_Save_db.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_Save_db.setStyleSheet("color: #1D0F03")
        self.pushButton_Save_db.setObjectName("pushButton_Save_db")
        self.pushButton_plus_asistent_db = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_plus_asistent_db.setGeometry(QtCore.QRect(520, 60, 41, 28))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_plus_asistent_db.setFont(font)
        self.pushButton_plus_asistent_db.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_plus_asistent_db.setStyleSheet("color: #42CA3D")
        self.pushButton_plus_asistent_db.setObjectName("pushButton_plus_asistent_db")
        self.pushButton_minus_lector_db = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_minus_lector_db.setGeometry(QtCore.QRect(230, 100, 41, 28))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_minus_lector_db.setFont(font)
        self.pushButton_minus_lector_db.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_minus_lector_db.setAutoFillBackground(False)
        self.pushButton_minus_lector_db.setStyleSheet("color: #DE2F23")
        self.pushButton_minus_lector_db.setObjectName("pushButton_minus_lector_db")
        self.pushButton_minus_assisstent_db = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_minus_assisstent_db.setGeometry(QtCore.QRect(520, 100, 41, 28))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_minus_assisstent_db.setFont(font)
        self.pushButton_minus_assisstent_db.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_minus_assisstent_db.setAutoFillBackground(False)
        self.pushButton_minus_assisstent_db.setStyleSheet("color: #DE2F23")
        self.pushButton_minus_assisstent_db.setObjectName("pushButton_minus_assisstent_db")
        self.lineEdit_Lector = QtWidgets.QLineEdit(self.tab_2)
        self.lineEdit_Lector.setGeometry(QtCore.QRect(20, 10, 251, 31))
        self.lineEdit_Lector.setStyleSheet("color: #1D0F03")
        self.lineEdit_Lector.setObjectName("lineEdit_Lector")
        self.lineEdit_Assisstent = QtWidgets.QLineEdit(self.tab_2)
        self.lineEdit_Assisstent.setGeometry(QtCore.QRect(310, 10, 251, 31))
        self.lineEdit_Assisstent.setStyleSheet("color: #1D0F03")
        self.lineEdit_Assisstent.setObjectName("lineEdit_Assisstent")
        self.listWidget_subjects_db = QtWidgets.QListWidget(self.tab_2)
        self.listWidget_subjects_db.setGeometry(QtCore.QRect(610, 60, 191, 191))
        self.listWidget_subjects_db.setStyleSheet("background-color: #91939C;")
        self.listWidget_subjects_db.setObjectName("listWidget_subjects_db")
        self.lineEdit_predmet = QtWidgets.QLineEdit(self.tab_2)
        self.lineEdit_predmet.setGeometry(QtCore.QRect(610, 10, 251, 31))
        self.lineEdit_predmet.setStyleSheet("color: #1D0F03")
        self.lineEdit_predmet.setObjectName("lineEdit_predmet")
        self.pushButton_plus_predmet_db = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_plus_predmet_db.setGeometry(QtCore.QRect(820, 60, 41, 28))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_plus_predmet_db.setFont(font)
        self.pushButton_plus_predmet_db.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_plus_predmet_db.setStyleSheet("color: #42CA3D")
        self.pushButton_plus_predmet_db.setObjectName("pushButton_plus_predmet_db")
        self.pushButton_minus_predmet_db = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_minus_predmet_db.setGeometry(QtCore.QRect(820, 100, 41, 28))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_minus_predmet_db.setFont(font)
        self.pushButton_minus_predmet_db.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_minus_predmet_db.setAutoFillBackground(False)
        self.pushButton_minus_predmet_db.setStyleSheet("color: #DE2F23")
        self.pushButton_minus_predmet_db.setObjectName("pushButton_minus_predmet_db")
        self.tabWidget.addTab(self.tab_2, "")
        self.label_lect_1sem = QtWidgets.QLabel(self.centralwidget)
        self.label_lect_1sem.setGeometry(QtCore.QRect(410, 470, 21, 16))
        self.label_lect_1sem.setObjectName("label_lect_1sem")
        self.label_lect_1sem_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_lect_1sem_2.setGeometry(QtCore.QRect(560, 470, 21, 16))
        self.label_lect_1sem_2.setObjectName("label_lect_1sem_2")
        self.label_lect_1sem_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_lect_1sem_3.setGeometry(QtCore.QRect(720, 470, 21, 16))
        self.label_lect_1sem_3.setObjectName("label_lect_1sem_3")
        self.label_lect_1sem_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_lect_1sem_4.setGeometry(QtCore.QRect(870, 470, 21, 16))
        self.label_lect_1sem_4.setObjectName("label_lect_1sem_4")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 990, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Навчальна робота кафедри"))
        self.pushButton.setText(_translate("MainWindow", "Відкрити"))
        self.pushButton_2.setText(_translate("MainWindow", "Відкрити"))
        self.pushButton_5.setText(_translate("MainWindow", "Порівняти"))
        self.pushButton_6.setText(_translate("MainWindow", "Створити звіт"))
        self.label_2.setText(_translate("MainWindow", "Файли кафедри"))
        self.label_3.setText(_translate("MainWindow", "Денна 1 семестр "))
        self.label_4.setText(_translate("MainWindow", "Денна 2 семестр"))
        self.label_5.setText(_translate("MainWindow", "Заочна 1 семестр"))
        self.label_6.setText(_translate("MainWindow", "Заочна 2 семестр"))
        self.pushButton_8.setToolTip(_translate("MainWindow", "<html><head/><body><p>XLS -> XLSX</p></body></html>"))
        self.pushButton_8.setText(_translate("MainWindow", "Конвертувати"))
        self.label_7.setToolTip(_translate("MainWindow", "<html><head/><body><p>Робочий навчальний план</p></body></html>"))
        self.label_7.setText(_translate("MainWindow", "РНП"))
        self.radioButton.setText(_translate("MainWindow", "Форма денна"))
        self.radioButton_2.setText(_translate("MainWindow", "Форма заочна"))
        self.label_8.setText(_translate("MainWindow", "           Предмети"))
        self.label_9.setText(_translate("MainWindow", "1 семестр часи:"))
        self.label_10.setText(_translate("MainWindow", "2 семестр часи:"))
        self.label_11.setText(_translate("MainWindow", "Лектора:"))
        self.label_12.setText(_translate("MainWindow", "Лектора:"))
        self.label_13.setText(_translate("MainWindow", "Асистента:"))
        self.label_14.setText(_translate("MainWindow", "Асистента:"))
        self.label_15.setText(_translate("MainWindow", "                Лектор"))
        self.label_16.setText(_translate("MainWindow", "              Асистент"))
        self.pushButton_plus_lector.setToolTip(_translate("MainWindow", "<html><head/><body><p align=\"center\">Додати до списку <span style=\" text-decoration: underline;\">лекторів</span></p></body></html>"))
        self.pushButton_plus_lector.setText(_translate("MainWindow", "+"))
        self.pushButton_plus_asistent.setToolTip(_translate("MainWindow", "<html><head/><body><p align=\"center\">Додати до списку <span style=\" text-decoration: underline;\">лекторів</span></p></body></html>"))
        self.pushButton_plus_asistent.setText(_translate("MainWindow", "+"))
        self.pushButton_minus_lector.setToolTip(_translate("MainWindow", "<html><head/><body><p align=\"center\">Видалити зі списку <span style=\" text-decoration: underline;\">лекторів</span></p></body></html>"))
        self.pushButton_minus_lector.setText(_translate("MainWindow", "x"))
        self.pushButton_minus_assisstent.setToolTip(_translate("MainWindow", "<html><head/><body><p align=\"center\">Видалити зі списку <span style=\" text-decoration: underline;\">асистент</span><span style=\" text-decoration: underline;\">ів</span></p></body></html>"))
        self.pushButton_minus_assisstent.setText(_translate("MainWindow", "x"))
        self.pushButton_Calculate_load.setText(_translate("MainWindow", "Розподілити\n"
"навантаження"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Розподілення"))
        self.pushButton_plus_lector_db.setToolTip(_translate("MainWindow", "<html><head/><body><p align=\"center\">Додати до списку <span style=\" text-decoration: underline;\">лекторів</span></p></body></html>"))
        self.pushButton_plus_lector_db.setText(_translate("MainWindow", "+"))
        self.pushButton_Save_db.setText(_translate("MainWindow", "Зберегти"))
        self.pushButton_plus_asistent_db.setToolTip(_translate("MainWindow", "<html><head/><body><p align=\"center\">Додати до списку <span style=\" text-decoration: underline;\">лекторів</span></p></body></html>"))
        self.pushButton_plus_asistent_db.setText(_translate("MainWindow", "+"))
        self.pushButton_minus_lector_db.setToolTip(_translate("MainWindow", "<html><head/><body><p align=\"center\">Видалити зі списку <span style=\" text-decoration: underline;\">лекторів</span></p></body></html>"))
        self.pushButton_minus_lector_db.setText(_translate("MainWindow", "x"))
        self.pushButton_minus_assisstent_db.setToolTip(_translate("MainWindow", "<html><head/><body><p align=\"center\">Видалити зі списку <span style=\" text-decoration: underline;\">асистент</span><span style=\" text-decoration: underline;\">ів</span></p></body></html>"))
        self.pushButton_minus_assisstent_db.setText(_translate("MainWindow", "x"))
        self.lineEdit_Lector.setPlaceholderText(_translate("MainWindow", "П.І.Б. лектора"))
        self.lineEdit_Assisstent.setPlaceholderText(_translate("MainWindow", "П.І.Б. асистента"))
        self.lineEdit_predmet.setPlaceholderText(_translate("MainWindow", "Назва предмета"))
        self.pushButton_plus_predmet_db.setToolTip(_translate("MainWindow", "<html><head/><body><p align=\"center\">Додати до списку <span style=\" text-decoration: underline;\">лекторів</span></p></body></html>"))
        self.pushButton_plus_predmet_db.setText(_translate("MainWindow", "+"))
        self.pushButton_minus_predmet_db.setToolTip(_translate("MainWindow", "<html><head/><body><p align=\"center\">Видалити зі списку <span style=\" text-decoration: underline;\">асистент</span><span style=\" text-decoration: underline;\">ів</span></p></body></html>"))
        self.pushButton_minus_predmet_db.setText(_translate("MainWindow", "x"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Редагування"))
        self.label_lect_1sem.setText(_translate("MainWindow", "0"))
        self.label_lect_1sem_2.setText(_translate("MainWindow", "0"))
        self.label_lect_1sem_3.setText(_translate("MainWindow", "0"))
        self.label_lect_1sem_4.setText(_translate("MainWindow", "0"))
